version: "3.9"
services:
  modbus-server:
    image: "laarouchioussama/modbus-server"
    depends_on:
      - mariadb
    restart: "always"
    ports:
      - "0.0.0.0:6651:6651/tcp"
    environment:
      - DEBUG_SHOW_VALUE=false
      - SERVER_PORT=6651    
      - SERVER_USE_RTU_OVER_TCP=true
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user_passwd
      - DATABASE_HOSTNAME=mariadb
      - DATABASE_DATABASE_NAME=modbus_rtu
      - DATABASE_SYNCHRONIZATION_INTERVAL=120    # Every 2 minutes
  mariadb:
    image: mariadb:10.7
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_passwd
      - MYSQL_PASSWORD=user_passwd
      - MYSQL_USER=user
      - MYSQL_DATABASE=modbus_rtu
  grafana:
    image: grafana/grafana
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_DATABASE_HOST=mariadb:3306
      - GF_DATABASE_NAME=modbus_rtu
      - GF_DATABASE_USER=user
      - GF_DATABASE_PASSWORD=user_passwd
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_MAX_OPEN_CONN=300
    ports:
      - "0.0.0.0:3000:3000"
  node-red:
    image: nodered/node-red
    depends_on:
      - mariadb
    restart: "always"
    ports:
      - "0.0.0.0:1880:1880"
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:
  grafana_data: {}
